// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2YOCHPdXDRE_GycmbYPB7KDmkXVC-h-A',
    appId: '1:1098624288012:web:4e70a13ffb28f629f97529',
    messagingSenderId: '1098624288012',
    projectId: 'medrx-mobile-app',
    authDomain: 'medrx-mobile-app.firebaseapp.com',
    storageBucket: 'medrx-mobile-app.appspot.com',
    measurementId: 'G-CXS67R1B2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGp_feqbR6_77wK-aHIHUzfTQ8_-2lXsY',
    appId: '1:1098624288012:android:88daaf367eff2892f97529',
    messagingSenderId: '1098624288012',
    projectId: 'medrx-mobile-app',
    storageBucket: 'medrx-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwN6T7bb6MxDRXxuSBP6nOEiKJAnzcYqA',
    appId: '1:1098624288012:ios:bc096e32373b15fef97529',
    messagingSenderId: '1098624288012',
    projectId: 'medrx-mobile-app',
    storageBucket: 'medrx-mobile-app.appspot.com',
    iosBundleId: 'com.example.medfastgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwN6T7bb6MxDRXxuSBP6nOEiKJAnzcYqA',
    appId: '1:1098624288012:ios:2a37dfbd80e61c25f97529',
    messagingSenderId: '1098624288012',
    projectId: 'medrx-mobile-app',
    storageBucket: 'medrx-mobile-app.appspot.com',
    iosBundleId: 'com.example.medfastgo.RunnerTests',
  );
}
